# spot-match configuration:

server:
  port: 8002

crypto:
  setting:
    load-symbols-from: db
  match:
    # which ip is slave (slave match engine will send delayed message to spot-clearing):
    slaveIp: 10.0.0.0
    snapshot:
      # directory that stores snapshots, MUST be writable:
      dir: /data/spot-match-snapshot
      # maximum number of snapshots (each symbol) that should be kept:
      max: 20
      # snapshot interval time, default to 600 seconds (10 minutes):
      interval: 600

spring:
  # master-slave data source config: same as api but smaller pool size:
  ex-rw-datasource:
    url: jdbc:mysql://${DB_EX_RW_HOST:${DB_RW_HOST:localhost}}/ex?useSSL=false&characterEncoding=utf8
    username: ex_rw
    password: ${DB_EX_RW_PASSWORD:ex_rw_password}
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      pool-name: HikariCP
      auto-commit: false
      connection-timeout: 5000
      validation-timeout: 3000
      max-lifetime: 600000
      maximum-pool-size: 10
      minimum-idle: 2
  # slave datasource:
  ex-ro-datasource:
    url: jdbc:mysql://${DB_EX_RO_HOST:${DB_RO_HOST:localhost}}/ex?useSSL=false&characterEncoding=utf8
    username: ex_ro
    password: ${DB_EX_RO_PASSWORD:ex_ro_password}
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      pool-name: HikariCP
      auto-commit: false
      connection-timeout: 5000
      validation-timeout: 3000
      max-lifetime: 600000
      maximum-pool-size: 10
      minimum-idle: 2
